name: CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
  MULTIPLE_REDIS_TEST_USE_REDIS: true
  MULTIPLE_REDIS_TEST_INTEGRATION_HOST1: localhost
  MULTIPLE_REDIS_TEST_INTEGRATION_HOST2: otherhost
  MULTIPLE_REDIS_TEST_INTEGRATION_PORTS: 7777,7778,6379
  MULTIPLE_REDIS_TEST_INTEGRATION_KILL_ENABLED: false
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['12.x', '14.x']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start Redis 1
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '5.x'
        redis-port: 6379
    - name: Start Redis 2
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '5.x'
        redis-port: 7777
    - name: Start Redis 3
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '5.x'
        redis-port: 7778
    - name: Install node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Run CI
      run: npm test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: './coverage/lcov.info'
