name: CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
  MULTIPLE_REDIS_TEST_USE_REDIS: true
  MULTIPLE_REDIS_TEST_INTEGRATION_HOST1: localhost
  MULTIPLE_REDIS_TEST_INTEGRATION_HOST2: otherhost
  MULTIPLE_REDIS_TEST_INTEGRATION_PORTS: 7777,7778,6379
  MULTIPLE_REDIS_TEST_INTEGRATION_CONF: /etc/redis/redis.conf
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['8.x', '10.x', '12.x', '14.x']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Setup Redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '5.x'
    - name: Startup Redis
      run: |
          chmod -R 777 ./test/helper/*.sh
          ./test/helper/start_redis.sh 7777 /etc/redis/redis.conf
          ./test/helper/start_redis.sh 7777 /etc/redis/redis.conf
    - name: Run CI
      run: npm test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: './target/coverage/report/lcov.info'
